# This file was auto-generated by Fern from our API Definition.

import typing

CompositionModeDto = typing.Union[
    typing.Literal["fluid", "strict_assembly", "composited_assembly", "fluid_assembly"],
    typing.Any,
]
