# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class FragmentTagUpdateParams(UniversalBaseModel):
    """
    Parameters for updating a fragment's tags.

    Allows adding new tags to and removing existing tags from a fragment.
    Both operations can be performed in a single request.
    """

    add: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional collection of tag ids to add to the fragment's tags
    """

    remove: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional collection of tag ids to remove from the fragment's tags
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
