# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .payload_kind_dto import PayloadKindDto
from .guideline_content import GuidelineContent
from .operation import Operation
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class GuidelinePayload(UniversalBaseModel):
    kind: PayloadKindDto = "guideline"
    content: GuidelineContent
    operation: Operation
    updated_id: typing.Optional[str] = None
    coherence_check: bool
    connection_proposition: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
