# This file was auto-generated by Fern from our API Definition.

import typing

GuidelineRelationshipKindDto = typing.Union[
    typing.Literal[
        "entailment", "precedence", "requirement", "priority", "persistence"
    ],
    typing.Any,
]
