# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .entity_type_dto import EntityTypeDto
from .guideline_relationship_kind_dto import GuidelineRelationshipKindDto
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class GuidelineRelationshipAddition(UniversalBaseModel):
    """
    Represents a guideline relationship addition.
    """

    source: str = pydantic.Field()
    """
    `id` of guideline or tag that is source or target of this relationship.
    """

    source_type: EntityTypeDto
    target: str = pydantic.Field()
    """
    `id` of guideline or tag that is source or target of this relationship.
    """

    target_type: EntityTypeDto
    kind: GuidelineRelationshipKindDto

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
