# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .interaction_kind_dto import InteractionKindDto
from .event_source_dto import EventSourceDto
import typing
from .tool_call import ToolCall
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Interaction(UniversalBaseModel):
    kind: InteractionKindDto = "message"
    source: EventSourceDto
    correlation_id: str
    data: typing.Optional[typing.Any] = None
    tool_calls: typing.List[ToolCall]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
