# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .guideline_invoice_data import GuidelineInvoiceData
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class InvoiceData(UniversalBaseModel):
    guideline: typing.Optional[GuidelineInvoiceData] = pydantic.Field(default=None)
    """
    Evaluation results for a Guideline, including contradiction checks and connection proposals
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
