# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .guideline_payload import GuidelinePayload
import typing
from .guideline_invoice_data import GuidelineInvoiceData
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Invoice(UniversalBaseModel):
    payload: GuidelinePayload
    checksum: str
    approved: bool
    data: typing.Optional[GuidelineInvoiceData] = None
    error: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
