# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .composition_mode_dto import CompositionModeDto
import datetime as dt
from .journey_node import JourneyNode
from .journey_edge import JourneyEdge
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class JourneyGraph(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the journey
    """

    title: str = pydantic.Field()
    """
    The title of the journey
    """

    description: str
    triggers: typing.List[str]
    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of tag IDs associated with the journey
    """

    composition_mode: typing.Optional[CompositionModeDto] = None
    labels: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Labels associated with the journey
    """

    priority: typing.Optional[int] = None
    last_modified: dt.datetime = pydantic.Field()
    """
    UTC timestamp of the last modification to the journey
    """

    nodes: typing.Optional[typing.List[JourneyNode]] = None
    edges: typing.Optional[typing.List[JourneyEdge]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
