# This file was auto-generated by Fern from our API Definition.

import typing
from .sdk_service_params import SdkServiceParams
from .open_api_service_params import OpenApiServiceParams

Params = typing.Union[SdkServiceParams, OpenApiServiceParams]
