# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class SdkServiceParams(UniversalBaseModel):
    """
    Configuration for SDK-based service integration
    """

    url: str = pydantic.Field()
    """
    Base URL for the service. Must include http:// or https:// scheme. The service must implement the Parlant SDK protocol.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
