# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .style_guide_coherence_check import StyleGuideCoherenceCheck
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class StyleGuideInvoiceData(UniversalBaseModel):
    """
    Evaluation results for a StyleGuide, including contradiction checks
    """

    coherence_checks: typing.List[StyleGuideCoherenceCheck]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
