# This file was auto-generated by Fern from our API Definition.

import typing

StyleGuideCoherenceCheckKindDto = typing.Union[
    typing.Literal[
        "contradiction_with_existing_style_guide",
        "contradiction_with_another_evaluated_style_guide",
    ],
    typing.Any,
]
