# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .style_guide_example import StyleGuideExample
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class StyleGuideContent(UniversalBaseModel):
    """
    Represents a style guide's content, including:

    - A 'principle' to highlight the main style guideline
    - One or more 'examples' illustrating correct and incorrect usage
    """

    principle: str = pydantic.Field()
    """
    A statement explaining the overarching style principle.
    """

    examples: typing.List[StyleGuideExample]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
