# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class TagsUpdateParams(UniversalBaseModel):
    """
    Parameters for updating a customer's tags.
    """

    add: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional collection of `TagId`s to add to the `Customer`'s `Tag`s
    """

    remove: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional collection of `TagId`s to remove from the `Customer`'s `Tag`s
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
